### ISSUE TITLE
广发纳斯达克100指数A美元(QDII) 未代销

### ISSUE THREAD

**Issue by Xhuangniu** [brain-zhang/xianglong#3]
想在且慢跟车,降龙组合
提醒广发纳斯达克100指数A美元(QDII)未代销。
请问有什么其他纳指的基金用于替换吗

**Comment by brain-zhang** [comment]
现在美股市场处于绝对高位；

降龙组合是我自己做的一个基准，只是用来检验其它策略的有效性；它是反人性的；

我自己在现在这个时候既不会买黄金，也不会买美股，也不会买沪深300；

投资有风险，要先学习，不管是谁的组合，不管是收益多么高的组合，都千万不要无脑跟；

**Comment by Xhuangniu** [comment]
> 现在美股市场处于绝对高位；
> 
> 降龙组合是我自己做的一个基准，只是用来检验其它策略的有效性；它是反人性的；虽然长期来看它是有效的，但我自己也做不到能严格执行纪律；
> 
> 我自己在现在这个时候既不会买黄金，也不会买美股，也不会买沪深300；
> 
> 投资有风险，要先学习，不管是谁的组合，不管是收益多么高的组合，都千万不要无脑跟；

好的 多谢。
